#!/bin/bash

# Check if the output directory argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <output_directory>"
  exit 1
fi

OUTPUT_DIR="$1"

# Create the provided directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Create the sequences.fa file with the specified content
cat > "$OUTPUT_DIR/sequences.fa" <<EOF
>CC-Hex2-AB-3-g
GSLKKIAKSLKKIAYSLKKIAQG:GSLEEIAKSLEEIAWSLEEIAQG:GSLKKIAKSLKKIAYSLKKIAQG:GSLEEIAKSLEEIAWSLEEIAQG:GSLKKIAKSLKKIAYSLKKIAQG:GSLEEIAKSLEEIAWSLEEIAQG
>CC-Hex2-AB-3-a
GLKKIAKSLKKIAYSLKKIAQSG:GLEEIAKSLEEIAWSLEEIAQSG:GLKKIAKSLKKIAYSLKKIAQSG:GLEEIAKSLEEIAWSLEEIAQSG:GLKKIAKSLKKIAYSLKKIAQSG:GLEEIAKSLEEIAWSLEEIAQSG
>CC-Hex2-AB-3-b
GKKIAKSLKKIAYSLKKIAQSLG:GEEIAKSLEEIAWSLEEIAQSLG:GKKIAKSLKKIAYSLKKIAQSLG:GEEIAKSLEEIAWSLEEIAQSLG:GKKIAKSLKKIAYSLKKIAQSLG:GEEIAKSLEEIAWSLEEIAQSLG
>CC-Hex2-AB-3-c
GKIAKSLKKIAYSLKKIAQSLKG:GEIAKSLEEIAWSLEEIAQSLEG:GKIAKSLKKIAYSLKKIAQSLKG:GEIAKSLEEIAWSLEEIAQSLEG:GKIAKSLKKIAYSLKKIAQSLKG:GEIAKSLEEIAWSLEEIAQSLEG
>CC-Hex2-AB-3-d
GIAKSLKKIAYSLKKIAQSLKKG:GIAKSLEEIAWSLEEIAQSLEEG:GIAKSLKKIAYSLKKIAQSLKKG:GIAKSLEEIAWSLEEIAQSLEEG:GIAKSLKKIAYSLKKIAQSLKKG:GIAKSLEEIAWSLEEIAQSLEEG
>CC-Hex2-AB-3-e
GAKSLKKIAYSLKKIAQSLKKIG:GAKSLEEIAWSLEEIAQSLEEIG:GAKSLKKIAYSLKKIAQSLKKIG:GAKSLEEIAWSLEEIAQSLEEIG:GAKSLKKIAYSLKKIAQSLKKIG:GAKSLEEIAWSLEEIAQSLEEIG
>CC-Hex2-AB-3-f
GKSLKKIAYSLKKIAQSLKKIAG:GKSLEEIAWSLEEIAQSLEEIAG:GKSLKKIAYSLKKIAQSLKKIAG:GKSLEEIAWSLEEIAQSLEEIAG:GKSLKKIAYSLKKIAQSLKKIAG:GKSLEEIAWSLEEIAQSLEEIAG
EOF

# Run the colabfold_batch command
colabfold_batch \
    --msa-mode single_sequence \
    --num-seeds 100 \
    "$OUTPUT_DIR/sequences.fa" \
    "$OUTPUT_DIR"
